[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Chilquinta profiles"
authors = [{name = "Ricardo", email = "ricardo.miranda-castillo@th-deg.de"}]
dynamic = ["version", "description"]
